name: Terraform Provisioning and Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  # =======================================
  # JOB 1: PROVISION INFRASTRUCTURE
  # =======================================
  provision:
    name: 'Terraform Provisioning'
    runs-on: ubuntu-latest
    
    # --------------------------------------------------------------------
    # KEY PART 1: This block makes the output available to other jobs.
    # --------------------------------------------------------------------
    outputs:
      instance_ip: ${{ steps.tf_apply.outputs.instance_public_ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        # --------------------------------------------------------------------
        # KEY PART 2: This ID is required to reference the step's output.
        # --------------------------------------------------------------------
        id: tf_apply 
        run: terraform apply -auto-approve
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}

  # =======================================
  # JOB 2: BUILD AND DEPLOY APPLICATION
  # =======================================
  deploy:
    name: 'Build and Deploy Application'
    runs-on: ubuntu-latest
    # --------------------------------------------------------------------
    # KEY PART 3: This tells the job to wait for 'provision' and to
    # expect outputs from it.
    # --------------------------------------------------------------------
    needs: provision 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: akash21357/technova-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          # --------------------------------------------------------------------
          # KEY PART 4: This is where the IP from the 'provision' job is used.
          # --------------------------------------------------------------------
          host: ${{ needs.provision.outputs.instance_ip }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop technova-app || true
            docker rm technova-app || true
            docker pull akash21357/technova-app:latest
            docker run -d --name technova-app -p 80:80 akash21357/technova-app:latest