name: Terraform Provisioning and Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  # =======================================
  # JOB 1: PROVISION INFRASTRUCTURE
  # =======================================
  provision:
    name: 'Terraform Provisioning'
    runs-on: ubuntu-latest
    
    outputs:
      instance_ip: ${{ steps.tf_apply.outputs.instance_public_ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        id: tf_apply # Give the step an ID to reference its output
        run: terraform apply -auto-approve

  # =======================================
  # JOB 2: BUILD AND DEPLOY APPLICATION
  # =======================================
  deploy:
    name: 'Build and Deploy Application'
    runs-on: ubuntu-latest
    needs: provision # This job will wait for the 'provision' job to succeed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # ... (Login to DockerHub, Build and Push image steps are exactly the same as before) ...
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: akash21357/technova-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ needs.provision.outputs.instance_ip }} # <-- Use the IP from the Terraform job!
          username: ubuntu # <-- User for Ubuntu AMIs
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop technova-app || true
            docker rm technova-app || true
            docker pull akash21357/technova-app:latest
            docker run -d --name technova-app -p 80:80 akash21357/technova-app:latest